//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
namespace University
{
    public abstract class Degree
    {
        protected string DegreeName;
        protected virtual int StartYear
        {
            get;
            set;
        }

        protected virtual int EndYear
        {
            get;
            set;
        }

        protected virtual List<Course> CourseList
        {
            get;
            set;
        }

        protected virtual bool AddCourse(Course course)
        {
            if (CourseList.Contains(course)) return false;
            else
            {
                CourseList.Add(course);
                return true;
            }
        }
        protected virtual void AddCourse(List<Course> courses)
        {
            foreach (Course course in courses)
            {
                AddCourse(course);
            }
        }
        protected virtual bool RemoveCourse(Course course)
        {
            if (!CourseList.Contains(course)) return false;
            else
            {
                CourseList.Remove(course);
                return true;
            }
        }

        protected virtual void ClearAllCourses()
        {
            CourseList.Clear();
        }
    }

}