//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Person
{
    /// <summary>
    /// Initializes a new instance of the <see cref="Person" /> class.
    /// </summary>
    protected Person()
        : this(null, null, 0, null) { }
    
    protected Person(string name, string surname, byte age, bool? gender)
    {
        this.Name = name;
        this.Surname = surname;
        this.Age = age;
        this.Gender = gender;
        this.Career = null;
        this.Income = 0m;
        this.HasPaidTaxes = false;
    }
    #region Fields

    public virtual bool HasPaidTaxes
	{
		get;
		private set;
	}

	public virtual Decimal Income
	{
		get;
		protected set;
	}

	public virtual string Name
	{
		get;
		private set;
	}

	public virtual string Surname
	{
		get;
		private set;
	}

	public virtual byte Age
	{
		get;
		private set;
	}

	public virtual bool? Gender
	{
		get;
		private set;
	}

	public virtual Career Career
	{
		get;
		private set;
	}
    #endregion // Fields
    public virtual bool PayTaxes()
	{
		throw new System.NotImplementedException();
	}

}

