//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using University;
public class Student : Person
{
    private Student()
        : this(null, null, 0, null, null, null) { }

    public Student(string name, string surname, byte age, bool? gender, string ID, Degree degree) 
        : base(name, surname, age, gender)
    {
        this.IdentificationNumber = ID;
        this.Degree = degree;
    }
	private string IdentificationNumber
	{
		get;
		set;
	}

	public virtual Degree Degree
	{
		get;
		set;
	}

	public virtual StudentCareer StudentCareer
	{
		get;
		set;
	}

}

